### ISSUE TITLE
Add support for LFS

### ISSUE THREAD

**Issue by bozaro** [bozaro/git-as-svn#68]
https://github.com/blog/1986-announcing-git-large-file-storage-lfs

Tasks:
- [X] Add git filter support #72
- [X] Create LFS filter with local directory backend #73
- [X] Patch gitlab for git-lfs-authenticate support #74
- [X] LFS server implementation for git users #75
- [ ] Use LFS-server as backend #76
- [X] Add LFS server permission check #92
- [X] Add support for change filtered file and .gitattributes in one commit #77 
- [X] Copy LFS metadata for forked GitLab repositories #94
- [X] Add batch API support #99

Bugs:
- [X] Filter change don't show in "svn log" #78

**Comment by slonopotamus** [comment]
We no longer need this issue. Since #222, we can work with GitLab LFS. The only item left here (#76) can be done on itself, without this tracker.
