### ISSUE TITLE
GitLab integration

### ISSUE THREAD

**Issue by bozaro** [bozaro/git-as-svn#91]
Tasks:
- [X] Add GitLab authenticator
- [X] Add GitLab repository list import on startup
- [X] Add GitLab per repository access control #88
- [X] Add repository list update without restart #89
- [ ] Add GitLab integration documentation #90
- [X] Copy LFS metadata for forked GitLab repositories #94

**Comment by valmont2k** [comment]
Cannot access to repo in gitlab 8.2.2 even after restart git-as-svn
error svn: E170001: You're not authorized to access this project
Cannot read users gitlab in groups
cannot add rights for author of repo

 INFO [qtp1661123505-23] (WebServer.java:103) - 192.168.0.10:53234 -  - "POST //gitlab.game-forest.com:8123/" 400 Can't parse event data
 WARN [qtp1661123505-24] (GitLabMappingConfig.java:154) - Can't read hook data
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "created_at" (class svnserver.ext.gitlab.mapping.GitLabHookEvent), not marked as ignorable (3 known properties: amespace"])
 at [Source: org.eclipse.jetty.server.Request$1@15a532e0; line: 1, column: 48] (through reference chain: svnserver.ext.gitlab.mapping.GitLabHookEvent["created_at"])
        at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:51) ~[jackson-databind-2.6.2.jar:2.6.2]
        at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:836) ~[jackson-databind-2.6.2.jar:2.6.2]
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1045) ~[jackson-databind-2.6.2.jar:2.6.2]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1352) ~[jackson-databind-2.6.2.jar:2.6.2]
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1330) ~[jackson-databind-2.6.2.jar:2.6.2]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:262) ~[jackson-databind-2.6.2.jar:2.6.2]
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:125) ~[jackson-databind-2.6.2.jar:2.6.2]
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3731) ~[jackson-databind-2.6.2.jar:2.6.2]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2771) ~[jackson-databind-2.6.2.jar:2.6.2]
        at svnserver.ext.gitlab.mapping.GitLabHookEvent.parseEvent(GitLabHookEvent.java:47) ~[git-as-svn.jar:?]
        at svnserver.ext.gitlab.mapping.GitLabMappingConfig$GitLabHookServlet.parseEvent(GitLabMappingConfig.java:152) [git-as-svn.jar:?]
        at svnserver.ext.gitlab.mapping.GitLabMappingConfig$GitLabHookServlet.doPost(GitLabMappingConfig.java:111) [git-as-svn.jar:?]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) [javax.servlet-api-3.1.0.jar:3.1.0]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [javax.servlet-api-3.1.0.jar:3.1.0]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:816) [jetty-servlet-9.3.0.v20150612.jar:9.3.0.v20150612]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583) [jetty-servlet-9.3.0.v20150612.jar:9.3.0.v20150612]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1121) [jetty-server-9.3.0.v20150612.jar:9.3.0.v20150612]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511) [jetty-servlet-9.3.0.v20150612.jar:9.3.0.v20150612]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1055) [jetty-server-9.3.0.v20150612.jar:9.3.0.v20150612]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.3.0.v20150612.jar:9.3.0.v20150612]
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109) [jetty-server-9.3.0.v20150612.jar:9.3.0.v20150612]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:118) [jetty-server-9.3.0.v20150612.jar:9.3.0.v20150612]
        at org.eclipse.jetty.server.Server.handle(Server.java:515) [jetty-server-9.3.0.v20150612.jar:9.3.0.v20150612]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:291) [jetty-server-9.3.0.v20150612.jar:9.3.0.v20150612]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242) [jetty-server-9.3.0.v20150612.jar:9.3.0.v20150612]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:238) [jetty-io-9.3.0.v20150612.jar:9.3.0.v20150612]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [jetty-io-9.3.0.v20150612.jar:9.3.0.v20150612]
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:57) [jetty-io-9.3.0.v20150612.jar:9.3.0.v20150612]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:191) [jetty-util-9.3.0.v20150612.jar:9.3.0.v20150612]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:126) [jetty-util-9.3.0.v20150612.jar:9.3.0.v20150612]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654) [jetty-util-9.3.0.v20150612.jar:9.3.0.v20150612]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572) [jetty-util-9.3.0.v20150612.jar:9.3.0.v20150612]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]

**Comment by bozaro** [comment]
@valmont2k 
Please don't add new problem to exists issues. Creating new issue mutch better.
